### ISSUE TITLE
Performance decrease when enable Multiple-GPU

### ISSUE THREAD

**Issue by ychding11** [owl-project/owl#95] opened 2021-05-27 13:36 UTC
- `nvidia-smi` output

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      On   | 00000000:07:00.0 Off |                    0 |
| N/A   52C    P0   286W / 400W |  33008MiB / 40537MiB |     93%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100-SXM4-40GB      On   | 00000000:0F:00.0 Off |                    0 |
| N/A   54C    P0   266W / 400W |  33268MiB / 40537MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  A100-SXM4-40GB      On   | 00000000:47:00.0 Off |                    0 |
| N/A   56C    P0   261W / 400W |  33268MiB / 40537MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  A100-SXM4-40GB      On   | 00000000:4E:00.0 Off |                    0 |
| N/A   54C    P0   275W / 400W |  33268MiB / 40537MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  A100-SXM4-40GB      On   | 00000000:87:00.0 Off |                    0 |
| N/A   65C    P0   291W / 400W |  33268MiB / 40537MiB |     99%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  A100-SXM4-40GB      On   | 00000000:90:00.0 Off |                    0 |
| N/A   66C    P0   198W / 400W |  33268MiB / 40537MiB |     90%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  A100-SXM4-40GB      On   | 00000000:B7:00.0 Off |                    0 |
| N/A   66C    P0   290W / 400W |  33268MiB / 40537MiB |     94%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  A100-SXM4-40GB      On   | 00000000:BD:00.0 Off |                    0 |
| N/A   67C    P0   296W / 400W |  33124MiB / 40537MiB |     95%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

```

- I create output buffer by `cudaMallocManaged(&fbPointer,newSize.x*newSize.y*sizeof(uint32_t));`
  - Is this the cause of performance decrease ?

**Comment by ingowald** [comment] 2021-08-01 17:51
It might be, depending on how big the output buffer is, and on how fast a single GPU can render. I'd be surprised if that's the case, though; could you give some more info on what exactly you're doing?

**Comment by ingowald** [comment] 2021-08-21 19:57
Cannot reproduce w/o more information - closing this.

**Closed by ingowald** 2021-08-21 19:57 UTC
