### ISSUE TITLE
Invalid Device Ordinal when CUDA_VISIBLE_DEVICES=1

### ISSUE THREAD

**Issue by n8vm** [owl-project/owl#54] opened 2020-06-06 17:22 UTC
Simplest way to reproduce is to run the interactive sample like this: `CUDA_VISIBLE_DEVICES=1 ./int01-simpleTriangles` . This Invalid Denice Ordinal error occurs in `groupBuildAccel` in DeviceGroup.cpp 

I don't seem to run into the same issue with CUDA_VISIBLE_DEVICES=1 ./sample01-simpleTriangles. However, I do see the above exception with ViSII

**Comment by ingowald** [comment] 2020-10-28 19:56
Bug has been root-caused to the display context running on different GPU than OWL; ie, this is not a bug in owl, but in the display/viewer code. Finally (in 1.0.2) fixed in owl's owlViewer helper library (which also fixes it in all owl samples and all owl apps that build on owlViewer), but apps that do their own display and cuda/gl resource sharing code will need their own fixes.

**Closed by ingowald** 2020-10-28 19:56 UTC
