### ISSUE TITLE
Build error: error C2668: 'owl::owlAsyncLaunch2D': ambiguous call to overloaded function

### ISSUE THREAD

**Issue by awiegersma** [owl-project/owl#86] opened 2021-04-11 10:36 UTC
I am getting a compiler error when building OWL under Visual Studio 2017, Windows 10

impl.cpp(174): error C2668: 'owl::owlAsyncLaunch2D': ambiguous call to overloaded function
impl.cpp(148): note: could be 'void owl::owlAsyncLaunch2D(OWLRayGen,int,int,OWLLaunchParams)'
owl_host.h(682): note: or       'void owlAsyncLaunch2D(OWLRayGen,int,int,OWLParams)' [found using argument-dependent lookup]
impl.cpp(174): note: while trying to match the argument list '(OWLRayGen, int, int, OWLLaunchParams)'

there are many more C2668 errors after this call ...

**Comment by awiegersma** [comment] 2021-04-11 18:48
It compiles and the examples run after defining the namespace in owl_host.h and removing some default arguments in the owlInstanceGroupCreate function from impl.cpp.

**Comment by ingowald** [comment] 2021-04-14 15:17
Hm. That doesn't sound right, though. owl-host.h should define the host-side _C linkage_ API, and that shouldn't contain a namespace. 

Unfortunately right now I only have VS19, so cannot reproduce, but still a few questions: You did use cmake to generate the proejct files, right? And what config did you try to compile that you ran into that? release/debug? 32/64? master/devel? any special cmake flags you used?

**Comment by ingowald** [comment] 2021-04-14 15:40
Huh. OK, confirmed. Just installed VS17, and I do in fact see those same errors (not on VS19, but on 17). Looking into it.

**Comment by ingowald** [comment] 2021-04-14 16:09
Hmpf. Seems VS17 is a bit more picky (or confused?) with C linkage functions defined in a namespace. The "problem" is that the API functions are declared without a namespace (as makes sense), but are then defined within a namespace. Since they all have C linkage that shouldn't matter (C linkage won't encode any namespace in the symbol mangling, anyway), and icc, clang, gcc, and vc19 are all just fine with that - but seems vs17 isn't. 

The solution I use right now is almost the reverse of what you've done: removing the "namespace owl {..." from impl.cpp, and instead adding "using namespace owl" (so the function bodies do find all the owl symbols).

Just fixed this in my local version, will do some more testing and then push this. There were a few other smaller issues with vs17 that i'd like to fix in the same push.

**Comment by awiegersma** [comment] 2021-04-14 16:12
Thanks for looking into this and for releasing OWL. It is a really useful library for my purpose.

**Comment by ingowald** [comment] 2021-04-14 17:02
It is indeed ... I don't think I've created a single project in at least a year that didn't even _start_ with git submodule add .... owl :-)

OK, closing this - latest master just compiled and ran fine on both vs17, vs19, and of course linux. Please let me know if this doesn't fix it (or similar issues occur) - I mostly use linux, and though I can _fix_ things in windows just fine I usually won't stumble over them myself, so relying on reports like this to even know if something doesn't work. Thx for reporting!

**Closed by ingowald** 2021-04-14 17:02 UTC
